name: esbuild Compilation & npm Publish Workflow

on:
  workflow_run:
    workflows:
      - create-github-release
    types:
      - completed
  workflow_dispatch:
    inputs:
      branch:
        description: 'Set the branch to use for automation tests'
        type: string
        required: false
        default: 'main'
      nodeVersion:
        description: version of node to use.  It's better to specify latest, lts/* or lts/-1 than to hardode numbers
        type: string
        default: lts/*
        required: false

jobs:
  bundle:
    if: ${{ inputs.branch || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')}}
    uses: ./.github/workflows/bundle.yml
    secrets: inherit
    with:
      branch: ${{ inputs.branch || 'main' }}
      nodeVersion: ${{ inputs.nodeVersion || 'lts/*'}}
  publish:
    needs: bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch || 'main' }}
      - name: Publish a Package
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
