name: Test External Projects
on:
  workflow_call:
    inputs:
      externalProjectGitUrl:
        description: "The url that will be cloned.  This contains the tests you want to run.  Ex: https://github.com/forcedotcom/templates"
        type: string
        required: true
      nodeVersion:
        required: false
        description: version of node to run tests against.  Use things like [lts/-1, lts/*, latest] to avoid hardcoding versions
        type: string
        default: lts/*
      os:
        required: false
        description: "runs-on property, ex: ubuntu-latest, windows-latest"
        type: string
        default: "ubuntu-latest"
      preExternalBuildCommands:
        required: false
        description: "commands to run before the build of the external repo...for example, to delete known module conflicts"
        type: string
        default: 'echo "no preExternalBuildCommands passed"'
      preSwapCommands:
        required: false
        description: "commands to run before ANY modifications happen. For example, changes that modify the lockfile like yarn add or remove need to happen before the action manually swaps the dependency under test"
        type: string
        default: 'echo "no preSwapCommands passed"'
      useCache:
        required: false
        type: boolean
        default: true
      attempts:
        required: false
        type: number
        default: 3
      bundledBranch:
        required: false
        description: Branch with the bundled version of core"
        type: string
        default: "main"

jobs:
  external-test:
    name: run tests
    runs-on: ${{ inputs.os }}
    steps:
      - name: Configure Git to handle long file paths on Windows
        if: ${{ runner.os == 'Windows' }}
        run: git config --system core.longpaths true
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}
      - name: Install CLI
        uses: salesforcecli/github-workflows/.github/actions/retry@main
        with:
          max_attempts: ${{ inputs.attempts }}
          command: npm install -g @salesforce/cli@nightly shx yarn-deduplicate --omit=dev
          timeout_minutes: 20
      - name: Checkout to external project
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.externalProjectGitUrl }}
      - name: Run yarn install
        uses: salesforcecli/github-workflows/.github/actions/yarnInstallWithRetries@main
      - name: Swap this dependency for the bundled version
        run: |
          yarn remove @salesforce/core
          yarn add forcedotcom/sfdx-core#${{ inputs.bundledBranch }}
          npx yarn-deduplicate
          yarn install  --network-timeout 600000
      - name: Build the external project (where the tests are)
        run: yarn build
      - name: Run tests with ${{ inputs.attempts }} attempts
        uses: salesforcecli/github-workflows/.github/actions/retry@main
        with:
          max_attempts: ${{ inputs.attempts }}
          command: yarn test
          retry_on: error
        env:
          SF_DISABLE_TELEMETRY: true
          DEBUG: ${{ vars.DEBUG }}
