name: Test Core Bundling
on:
  push:
    branches-ignore: [main]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Set the branch to bundle core'
        required: false
        type: string
      nodeVersion:
        description: version of node to use.  It's better to specify latest, lts/* or lts/-1 than to hardode numbers
        type: string
        default: lts/*
        required: false

jobs:
  bundle:
    uses: ./.github/workflows/bundle.yml
    with:
      branch: ${{ github.ref_name || inputs.branch }}
      nodeVersion: ${{ inputs.nodeVersion }}
  tests:
    needs: bundle
    uses: ./.github/workflows/testExternalProjects.yml
    secrets: inherit
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest']
        externalProjectGitUrl:
          - https://github.com/forcedotcom/salesforcedx-templates
          - https://github.com/forcedotcom/salesforcedx-apex
    with:
      externalProjectGitUrl: ${{ matrix.externalProjectGitUrl }}
      os: ${{ matrix.os }}
      useCache: false
      bundledBranch: ${{ github.ref_name }}
      preSwapCommands: 'yarn upgrade @jsforce/jsforce-node@latest; npx yarn-deduplicate; yarn install'
      preExternalBuildCommands: 'shx rm -rf node_modules/@salesforce/core/node_modules/@jsforce/jsforce-node shx rm -rf node_modules/@salesforce/sf-plugins-core/node_modules/@salesforce/core node_modules/@salesforce/cli-plugins-testkit/node_modules/@salesforce/core node_modules/@salesforce/source-tracking/node_modules/@salesforce/core node_modules/@salesforce/source-deploy-retrieve/node_modules/@salesforce/core node_modules/@salesforce/apex-node/node_modules/@salesforce/core'
